import { Item } from '../types/items';

export const items: Item[] = [
    { id: 1, name: 'Bread', price: 10 },
    { id: 2, name: 'Eggs', price: 5 },
    { id: 3, name: 'Beacon', price: 10 },
    { id: 4, name: 'Steak', price: 25 },
    { id: 5, name: 'Coffee', price: 25 },
    { id: 6, name: 'Chicken', price: 35 },
    { id: 7, name: 'Hash', price: 15 },
    { id: 5, name: 'Coffee', price: 25 },
    { id: 6, name: 'Chicken', price: 35 },
    { id: 7, name: 'Hash', price: 15 },
    { id: 8, name: 'Beans', price: 15 },
    { id: 9, name: 'Whiskey', price: 20 },
    { id: 10, name: 'Cheese', price: 10 },
    { id: 11, name: 'Anti-Venom', price: 150 },
    { id: 12, name: 'Skillet', price: 25 },
    { id: 13, name: 'Fish Hooks', price: 20 },
    { id: 14, name: 'Coffee Pot', price: 35 },
    { id: 15, name: 'Knife', price: 20 },
    { id: 16, name: 'Pan', price: 35 },
    { id: 17, name: 'Gloves', price: 10 },
    { id: 18, name: 'Rope', price: 30 },
    { id: 19, name: 'Lantern', price: 20 },
    { id: 20, name: 'Blanket', price: 30 },
    { id: 21, name: 'Matches', price: 5 },
    { id: 19, name: 'Lantern', price: 20 },
    { id: 20, name: 'Blanket', price: 30 },
    { id: 21, name: 'Matches', price: 5 },
    { id: 22, name: 'Pick', price: 65 },
    { id: 23, name: 'Shovel', price: 50 },
    { id: 24, name: 'Map', price: 10 },
    { id: 25, name: 'Revolver', price: 200 },
    { id: 26, name: 'Bullets', price: 50 },
    { id: 27, name: 'Long Johns', price: 20 },
    { id: 28, name: 'Empty Canteen', price: 15 },
    { id: 29, name: 'Full Canteen', price: 0 },
    { id: 30, name: 'Snake', price: 0 },
    { id: 31, name: 'Small Fish', price: 0 },
    { id: 32, name: 'Big Fish', price: 0 },
    { id: 33, name: 'Small Bag of Gold Grade 0', price: 0 },
    { id: 34, name: 'Small Bag of Gold Grade 1', price: 1 },
    { id: 35, name: 'Small Bag of Gold Grade 2', price: 2 },
    { id: 36, name: 'Small Bag of Gold Grade 3', price: 3 },
    { id: 37, name: 'Small Bag of Gold Grade 4', price: 4 },
    { id: 38, name: 'Big Bag of Gold Grade 0', price: 0 },
    { id: 39, name: 'Big Bag of Gold Grade 1', price: 1 },
    { id: 40, name: 'Big Bag of Gold Grade 2', price: 2 },
    { id: 41, name: 'Big Bag of Gold Grade 3', price: 3 },
    { id: 42, name: 'Big Bag of Gold Grade 4', price:  4}
];